import { useState, useEffect, useRef } from 'react';

// Figma asset URLs
const durableScreenshot = "https://www.figma.com/api/mcp/asset/500c276b-b412-4494-8237-76f3146f55e5";

interface PlatformData {
  id: string;
  label: string;
  score: number;
  scoreColor: string;
  badge: string;
  badgeBg: string;
  badgeColor: string;
  name: string;
  description: string;
  screenshot: string | null;
  screenshotBg: string;
  highlights: string[];
}

const platforms: PlatformData[] = [
  {
    id: 'durable',
    label: 'Durable',
    score: 90,
    scoreColor: '#519a73',
    badge: 'Best overall',
    badgeBg: 'rgba(73,138,103,0.2)',
    badgeColor: '#3e7457',
    name: 'Durable',
    description: 'Scroll to explore',
    screenshot: durableScreenshot,
    screenshotBg: 'bg-black/[0.03]',
    highlights: [
      'Clarity, Copy Quality, Trust & SEO all scored 100',
      'Lighthouse SEO scored 100 on both desktop and mobile',
      'Mobile layout holds well — readable text and a working hamburger menu',
      'Only one axe-core issue flagged — minor button text visibility',
      'Contact page, About page and social media buttons included by default',
      'Production-ready. Just edit services, pricing, and contact info.',
    ],
  },
  {
    id: 'wix',
    label: 'Wix Harmony',
    score: 82,
    scoreColor: '#519a73',
    badge: 'Runner up',
    badgeBg: 'rgba(73,138,103,0.2)',
    badgeColor: '#3e7457',
    name: 'Wix Harmony',
    description: 'Scroll to explore',
    screenshot: null,
    screenshotBg: 'bg-[#f0f4f8]',
    highlights: [
      'Strong CTA placement — "Book Now" visible above the fold',
      'Lighthouse SEO scored 88 on desktop, 79 on mobile',
      'Good mobile responsiveness with collapsible nav',
      'Multiple accessibility issues flagged — missing alt text and labels',
      'Requires manual setup for About and Contact pages',
      'Needs minor copy edits before going live — generic placeholder text.',
    ],
  },
  {
    id: 'squarespace',
    label: 'Squarespace',
    score: 72,
    scoreColor: '#fb9f28',
    badge: 'Fair',
    badgeBg: 'rgba(251,159,40,0.2)',
    badgeColor: '#9f4c04',
    name: 'Squarespace',
    description: 'Scroll to explore',
    screenshot: null,
    screenshotBg: 'bg-[#f5f0eb]',
    highlights: [
      'Beautiful template design — strong visual hierarchy',
      'Copy was generic and not tailored to the business type',
      'Mobile layout breaks on narrow screens — text overlap on hero',
      'Lighthouse SEO scored 75 — missing meta descriptions',
      'No Contact or About page generated by default',
      'Significant manual editing required before production launch.',
    ],
  },
];

function SmallScoreCircle({ score, color }: { score: number; color: string }) {
  const r = 22;
  const cx = 28;
  const cy = 28;
  const circumference = 2 * Math.PI * r;
  const progress = (score / 100) * circumference;
  return (
    <div className="relative w-[56px] h-[56px]">
      <svg width="56" height="56" viewBox="0 0 56 56">
        <circle cx={cx} cy={cy} r={r} fill="none" stroke="rgba(0,0,0,0.08)" strokeWidth="4" />
        <circle
          cx={cx} cy={cy} r={r}
          fill="none"
          stroke={color}
          strokeWidth="4"
          strokeLinecap="round"
          strokeDasharray={`${progress} ${circumference}`}
          strokeDashoffset={circumference / 4}
          transform={`rotate(-90 ${cx} ${cy})`}
          style={{ transition: 'stroke-dasharray 0.5s ease, stroke 0.5s ease' }}
        />
      </svg>
      <span className="absolute inset-0 flex items-center justify-center text-[14px] font-semibold text-black/80">{score}</span>
    </div>
  );
}

export default function DifferenceSection() {
  const [activeId, setActiveId] = useState('durable');
  const [visibleId, setVisibleId] = useState('durable');
  const [visible, setVisible] = useState(true);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  function handleTabChange(id: string) {
    if (id === activeId) return;
    if (timerRef.current) clearTimeout(timerRef.current);
    setVisible(false);
    setActiveId(id);
    timerRef.current = setTimeout(() => {
      setVisibleId(id);
      setVisible(true);
    }, 220);
  }

  useEffect(() => () => { if (timerRef.current) clearTimeout(timerRef.current); }, []);

  const platform = platforms.find(p => p.id === visibleId)!;

  return (
    <section className="pb-16 md:pb-32 flex flex-col items-center px-4 md:px-6">
      <div className="max-w-[1200px] w-full flex flex-col gap-8 md:gap-12 items-center">
        {/* Header */}
        <div className="flex flex-col gap-8 md:gap-14 items-center w-full md:w-[480px]">
          <div className="flex flex-col gap-4 items-center w-full">
            <div className="flex flex-col gap-4 items-center text-center">
              <p className="text-[14px] font-semibold leading-5 text-[#7d5d9a]">Real Examples</p>
              <h2 className="font-display text-[48px] leading-[44px] md:text-[72px] md:leading-[68px] text-black/80">
                See the difference yourself
              </h2>
              <p className="text-[16px] md:text-[14px] leading-6 text-black/55">
                We built the same landscaping business on every platform using their AI or fastest setup option. Here's what each one produced.
              </p>
            </div>
          </div>

          {/* Platform tabs */}
          <div className="flex items-center gap-2">
            {platforms.map(p => (
              <button
                key={p.id}
                onClick={() => handleTabChange(p.id)}
                className={`h-12 px-5 py-3 rounded-3xl text-[16px] font-semibold transition-colors ${
                  activeId === p.id
                    ? 'bg-black/80 text-white/80'
                    : 'bg-black/[0.03] text-black/80 hover:bg-black/[0.06]'
                }`}
              >
                {p.label}
              </button>
            ))}
          </div>
        </div>

        {/* Main content */}
        <div
          className="flex flex-col md:flex-row gap-4 items-stretch w-full"
          style={{
            opacity: visible ? 1 : 0,
            transition: 'opacity 0.22s ease',
          }}
        >
          {/* Screenshot panel */}
          <div className={`${platform.screenshotBg} rounded-3xl relative overflow-hidden md:flex-shrink-0 w-full md:w-[795px] h-[260px] md:h-[544px] transition-colors duration-500`}>
            {/* Window dots */}
            <div className="absolute left-[17px] top-[14px] w-2 h-2 rounded-full bg-black/10" />
            <div className="absolute left-[31px] top-[14px] w-2 h-2 rounded-full bg-black/10" />
            <div className="absolute left-[45px] top-[14px] w-2 h-2 rounded-full bg-black/10" />
            {/* Screenshot */}
            <div className="absolute top-8 left-2 right-2 bottom-2 rounded-2xl overflow-hidden shadow-xl">
              {platform.screenshot ? (
                <img
                  src={platform.screenshot}
                  alt={`${platform.name} website example`}
                  className="w-full h-full object-cover rounded-2xl"
                />
              ) : (
                <div className="w-full h-full rounded-2xl bg-white/60 flex items-center justify-center">
                  <span className="text-[14px] text-black/30 font-medium">{platform.name} website preview</span>
                </div>
              )}
            </div>
          </div>

          {/* Highlights panel */}
          <div className="flex-1 bg-black/[0.03] rounded-3xl p-6 md:p-8 flex flex-col gap-6 md:gap-8">
            {/* Header */}
            <div className="flex flex-col gap-0.5">
              <span
                className="text-[12px] font-medium rounded-full px-2 py-0.5 self-start"
                style={{ backgroundColor: platform.badgeBg, color: platform.badgeColor }}
              >
                {platform.badge}
              </span>
              <div className="flex items-end justify-between mt-1">
                <div className="flex flex-col gap-1">
                  <p className="text-[16px] font-semibold text-black/80">{platform.name}</p>
                  <p className="text-[14px] text-black/80">{platform.description}</p>
                </div>
                <SmallScoreCircle score={platform.score} color={platform.scoreColor} />
              </div>
            </div>

            {/* Highlights list */}
            <div className="flex flex-col gap-4">
              <p className="text-[16px] font-semibold text-black/80">Highlights</p>
              <div className="flex flex-col gap-4">
                {platform.highlights.map((h, i) => (
                  <div key={i} className="flex gap-3 items-start">
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" className="flex-shrink-0 mt-0.5">
                      <path d="M4 10L8 14L16 6" stroke="rgba(0,0,0,0.8)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                    <p className="text-[14px] font-medium leading-5 text-black/80">{h}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
